---

name: Preset PR
on:
  pull_request:
    types: [opened, reopened]
run-name: ${{ github.workflow }} (${{ github.ref_name }})
jobs:
  set-assignees:
    runs-on: ubuntu-latest
    if: ${{ toJSON(github.event.pull_request.assignees) == '[]' }}
    steps:
      - name: Set assignees
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: `${{ github.actor }}`
            });
  set-reviewers:
    runs-on: ubuntu-latest
    if: ${{ toJSON(github.event.pull_request.requested_reviewers) == '[]' && github.actor == 'dependabot[bot]' }}
    steps:
      - name: Set reviewers
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reviewers = ['jnicrimi'];
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers
            });
  notification:
    runs-on: ubuntu-latest
    needs: [set-assignees, set-reviewers]
    if: ${{ always() }}
    steps:
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "*Pull request opened*\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<@U01C4AD5CP7>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Pull request opened*\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTIONS_BOT_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
