---

name: Preset PR
on:
  pull_request:
    types: [opened, reopened]
run-name: ${{ github.workflow }} (${{ github.ref_name }})
jobs:
  set-assignees:
    runs-on: ubuntu-latest
    steps:
      - name: Set assignees
        uses: actions/github-script@v6
        if: ${{ toJSON(github.event.pull_request.assignees) == '[]' }} && ${{ github.actor != 'dependabot[bot]' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: `${{ github.actor }}`
            });
  notification:
    runs-on: ubuntu-latest
    needs: [set-assignees]
    if: ${{ success() }}
    steps:
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "*Pull request opened*\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Pull request opened*\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*assignees*\n${{ github.actor }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTIONS_BOT_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
